### ISSUE TITLE
error when installing after updating sublime text 3

### ISSUE THREAD

**Issue by PredatorFly** [evandrocoan/AmxxEditor#13]

**Comment by evandrocoan** [comment]
What error? Can you post here the contents of your Sublime Text console?

You can open the console by going on the menu: `Preferences -> Show Console`

**Comment by evandrocoan** [comment]
* Correction: the menu is: `View -> Show Console`

**Comment by evandrocoan** [comment]
I recently renamed the external dependency of `debug_tools` from `DebugTools` to `debugtools`. This is pending to be renamed here:
1. https://github.com/wbond/package_control_channel/pull/7389 Fixed my dependencies URLs names not on lowercase convention

A quick fix should be manually installing the `debug_tools` dependency. Package Control is not much friendly and does require some extra work from the user in order to do it.

Try this:
1. Go to the menu `Preferences -> Package Control`
1. Type `Add Channel` on the opened quick panel and press enter
1. Then enter the following address and press enter:
   ```
   https://raw.githubusercontent.com/evandrocoan/SublimeStudioChannel/master/channel.json
   ```
1. Open the Sublime Text command palette and run the command `Package Control Satisfy Dependencies`
1. Then, open your Sublime Text console and check when the command has finished to run.

**Comment by PredatorFly** [comment]
work now, thx!
