### ISSUE TITLE
Autocompletion issue

### ISSUE THREAD

**Issue by CrazY770** [evandrocoan/AmxxEditor#9]
Hello, I  found a bug with autocompletion. If I type something right after the first parenthesis "(bla" without a spacing "( bla" autocompletion does not work.

**Comment by Mc-Happy** [comment]
Hi,
I also have this problem.
Due to the fact that I consider this a very troublesome thing, i decided to make some code-research.
It seems that the problem lies in the [382](https://github.com/evandrocoan/AmxxEditor/blob/master/Amxmodx.py#L382) - [384](https://github.com/evandrocoan/AmxxEditor/blob/master/Amxmodx.py#L384) lines of the [Amxmodx.py](https://github.com/evandrocoan/AmxxEditor/blob/master/Amxmodx.py) which are related to SublimeTextIssues/core#819:
```
# temporarily masking word_separators
# https://github.com/SublimeTextIssues/Core/issues/819
```
A quick solution is to comment on the above-mentioned lines but I haven't checked whether this will have a negative impact on the other plugin functionalities.

**Comment by xpt1x** [comment]
Yes this is a bug, even with constants too
Suppose Constant is **g_xyz**

**TYPING STYLE 1** :  `if(g_xyz)`  _Auto Completion Wont Work_
**TYPING STYLE 2** : `if( g_xyz)` _Auto Completion Will Work_

**Comment by evandrocoan** [comment]
It should be fixed on the next version. It will be released when this pull request gets merged: https://github.com/wbond/package_control_channel/pull/7193
